<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Vox</AssemblyName>
    <RootNamespace>Vox</RootNamespace>
    <Version>1.1.0</Version>
    <ApplicationIcon>Vox.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Vox.ico" />
    <Resource Include="Vox.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="tests\**\*.cs" />
    <Compile Remove="VoxSetup\**\*.cs" />
    <Compile Remove="VoxSetup\**\*.xaml.cs" />
    <None Remove="VoxSetup\**\*.*" />
    <Page Remove="VoxSetup\**\*.*" />
    <Resource Remove="VoxSetup\**\*.*" />
  </ItemGroup>

</Project>
